#!/bin/bash
# GCP IAM Role Migration Commands
# This script provides the gcloud commands to migrate from over-privileged roles to custom roles

PROJECT_ID="foiply-app"

echo "================================================================================"
echo "GCP IAM ROLE MIGRATION COMMANDS"
echo "================================================================================"
echo "Project: $PROJECT_ID"
echo ""

echo "🔧 STEP 1: Create Custom Roles"
echo "----------------------------------------"
echo "Run: python deploy_custom_roles.py"
echo ""

echo "🔄 STEP 2: Migrate Service Accounts (Examples)"
echo "----------------------------------------"

echo ""
echo "# Container Admin -> Container Viewer (CRITICAL - 96% permission reduction)"
echo "# Remove dangerous container.admin role from service accounts"
echo ""
echo "gcloud projects remove-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:gsa-fusion-staging@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='roles/container.admin'"
echo ""
echo "gcloud projects add-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:gsa-fusion-staging@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='projects/foiply-app/roles/custom_container_viewer'"
echo ""

echo "# Compute Viewer -> Compute Monitor (for monitoring tools like Datadog)"
echo "gcloud projects remove-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:datadog-118@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='roles/compute.viewer'"
echo ""
echo "gcloud projects add-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:datadog-118@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='projects/foiply-app/roles/custom_compute_monitor'"
echo ""

echo "# Secret Manager Admin -> Secret Reader (CRITICAL - 81% permission reduction)"
echo "gcloud projects remove-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:devops-workstations@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='roles/secretmanager.admin'"
echo ""
echo "gcloud projects add-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:devops-workstations@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='projects/foiply-app/roles/custom_secret_reader'"
echo ""

echo "# Storage Object Admin -> Storage Reader"
echo "gcloud projects remove-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:cloud-sql@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='roles/storage.objectAdmin'"
echo ""
echo "gcloud projects add-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:cloud-sql@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='projects/foiply-app/roles/custom_storage_reader'"
echo ""

echo "🗑️ STEP 3: Remove Completely Unused Roles"
echo "----------------------------------------"
echo "# These accounts have 100% unused permissions - consider removing entirely:"
echo ""
echo "# Remove unused network connectivity role"
echo "gcloud projects remove-iam-policy-binding $PROJECT_ID \\"
echo "  --member='user:sandra.gendy@documo.com' \\"
echo "  --role='roles/networkconnectivity.groupUser'"
echo ""

echo "# Remove unused secret accessor roles"
echo "gcloud projects remove-iam-policy-binding $PROJECT_ID \\"
echo "  --member='serviceAccount:xfs-production@foiply-app.iam.gserviceaccount.com' \\"
echo "  --role='roles/secretmanager.secretAccessor'"
echo ""

echo "⚠️  STEP 4: Validation Commands" 
echo "----------------------------------------"
echo "# Test each service account after migration:"
echo ""
echo "# List current roles for a service account"
echo "gcloud projects get-iam-policy $PROJECT_ID \\"
echo "  --flatten='bindings[].members' \\"
echo "  --format='table(bindings.role)' \\"
echo "  --filter='bindings.members:serviceAccount:gsa-fusion-staging@foiply-app.iam.gserviceaccount.com'"
echo ""

echo "# Test custom role permissions"
echo "gcloud iam roles describe custom_container_viewer --project=$PROJECT_ID"
echo ""

echo "📊 STEP 5: Monitor Applications"
echo "----------------------------------------"
echo "# After migration, monitor logs for permission denied errors:"
echo "gcloud logging read 'protoPayload.authenticationInfo.principalEmail:(\"gsa-fusion-staging@foiply-app.iam.gserviceaccount.com\") AND severity=ERROR' \\"
echo "  --limit=50 \\"
echo "  --format='table(timestamp,protoPayload.methodName,protoPayload.status.message)'"
echo ""

echo "================================================================================"
echo "🚨 SECURITY IMPACT SUMMARY:"
echo "- Container Admin: 429 → 15 permissions (96% reduction)"
echo "- Compute Viewer: 354 → 20 permissions (94% reduction)" 
echo "- Secret Manager Admin: 27 → 5 permissions (81% reduction)"
echo "- Storage Object Admin: 28 → 10 permissions (64% reduction)"
echo ""
echo "Total permission exposure reduced by ~90%!"
echo "================================================================================"